package br.com.study.resource;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.Response;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
@Path("pdf")
public class GeneratePDFResource {

    @GET
    @Produces("application/pdf")
    public Response getPdf() {
        try {
            // Create a new PDF document
            PDDocument document = new PDDocument();
            PDPage page = new PDPage();
            document.addPage(page);

            // Write some text to the PDF
            PDPageContentStream contentStream = new PDPageContentStream(document, page);
            contentStream.beginText();
            contentStream.setFont(PDType1Font.HELVETICA, 12);
            contentStream.newLineAtOffset(100, 700);
            contentStream.showText("Hello, this is a PDF generated by Quarkus!");
            contentStream.endText();
            contentStream.close();

            // Convert the PDF document to a byte array
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            document.save(byteArrayOutputStream);
            document.close();
            byte[] pdfBytes = byteArrayOutputStream.toByteArray();

            // Return the PDF file as a response
            return Response.ok(pdfBytes)
                    .header("Content-Disposition", "attachment; filename=example.pdf")
                    .build();
        } catch (IOException e) {
            // Handle exception
            e.printStackTrace();
            return Response.serverError().build();
        }
    }
}
